### PR TITLE
Sherfey updates

### PR DESCRIPTION
**Pull request by jsherfey**
Merging major changes that include adding the DynaSim GUI, support for event tracking and event-based model updating (e.g., STDP), Windows-compatibility, and storing mechanism equations in the specification structure.

### CODE REVIEW

**Comment by asoplata** [comment]
Cluster jobs currently do not work with this. They are properly submitted, but in each `sim_job<N>.m` file, there is an empty `addpath ` line that causes the simulation to fail.

**Comment by jsherfey** [comment]
That is fixed in the most recent version of sherfey_updates. Those fixes
are not present in the version in the pull request though.


On Jul 10, 2017 12:22 PM, "Austin Soplata" <notifications@github.com> wrote:

Cluster jobs currently do not work with this. They are properly submitted,
but in each sim_job<N>.m file, there is an empty addpath line that causes
the simulation to fail.

—
You are receiving this because you authored the thread.

Reply to this email directly, view it on GitHub
<https://github.com/DynaSim/DynaSim/pull/197#issuecomment-314158264>, or mute
the thread

**Comment by asoplata** [comment]
Using the compiler on a cluster job under this branch still doesn't work, see #198

**Comment by asoplata** [comment]
@jsherfey I am using the current version of `sherfey_branch`, last commit 34a2e8d (merging 028e989 1fa1bc8). I downloaded the code for this branch roughly three hours ago, so I don't understand -- is there code that is not currently on `sherfey_branch`? As far as I can tell, the current code on `sherfey_branch`, which is 2 days old, IS in this PR.

**Comment by asoplata** [comment]
Wait, is `sherfey_updates` currently incomplete, and not ready to be reviewed in its current form? Is the code for the PR not finished?

**Comment by erik-roberts** [comment]
ba1e73c

**Comment by erik-roberts** [comment]
@jsherfey good?

**Comment by jsherfey** [comment]
The dev branch now has dependencies split into two directories:

dynasim/dependencies (with MDD and MDD_SM @ f611825)
dynasim/functions/dependencies (with everything else)

Is there some way to move MDD* into dynasim/functions/dependencies? I'm not
sure why that didn't work...

**Comment by asoplata** [comment]
Awesome! Compiling on the cluster etc. all seem to work now. I'm now using branch `[benchmark_2017_v2](https://github.com/DynaSim/DynaSim/tree/benchmark_2017_v2)` to run a completely new set of DynaSim benchmarks, including with compilation. I still have benchmark data (1/sim) from almost every non-compiled benchmark before Jason's changes.

**Pull request merged**
