### PR TITLE
Adding access to all state variables, not just the first

### PR DESCRIPTION
**Pull request by kupiqu**
I implemented a rate model that needs access to not only synaptic gating variables but also the instantaneous firing rate. Hence I made a change in the code so all the state variables in the scope are accessible.

The way it works is by adding a suffix `_stvar_#` where `#` is the state variable number: 1, 2, ...

Could any of you, @jsherfey @erik-roberts or @asoplata, please take a look and approve the pull request?

Thanks

### CODE REVIEW

**Comment by jsherfey** [comment]
Could you provide an example that illustrates what you are trying to do?
I'm wondering if what you need is already supported but just poorly
documented.

**Comment by kupiqu** [comment]
I am trying to implement Ardid and Wang, J Neurosci 2013 in DynaSim

For this DynaSim needs some additional features and I'm still trying to figure out how to do this, but wrt this pull request the idea is the following:

There is a ODE for the NMDA gating variable (sNMDA), which depends on instantaneous FRs (insFR). The inst FRs are calculated from a fIcurve from the total input current.

Input currents are background inputs, stimulus inputs, synaptics inputs (computed from sNMDA) and adaptation current, which depends on instFR.

I could not find a way to use a link for the instFR (I guess because recurrences), but that's not a big deal, as I could generate a second ODE for the instFR that updates its values out of the fIcurve with a very fast time constant.

Now the thing is that some inputs (synaptic) depend on first ODE (sNMDA), whereas other inputs (adaptation) depend on the second ODE (instFR).

As far as I know there is no way to access a second (or successive state variables), only the first (e.g., X, which is replaced by the first state variable).

This change allows accessing the first and subsequent state variables by using e.g., X_stvar_1, X_stvar_2, etc.

**Comment by jsherfey** [comment]
You should be able to access the state variable using its explicit name. X is an alias to the first state variable in the master equation. However, all state variables should be accessible directly using the name of the population state variable within a mechanism of that population.

Example:
If your master equation is 
```
spec.populations.equations={
'dV/dt= @M -V; V(0)=-65;'
'ds/dt = -s+V;  s(0)=2;'
}
```
Then you should be able to access s directly in a mechanism M.mech: 
```
y(s)=s;
@M += y; 
monitor y
```
The results of y and s should be the same:
```
data=dsSimulate(spec);
figure
subplot(2,1,1); plot(data.time, data.pop1_s)
subplot(2,1,2); plot(data.time, data.pop1_M_y)
```
Are you trying to do something different from this?

**Comment by kupiqu** [comment]
I tried what you mentioned and DynaSim complained about it:

Ok, let's be more explicit, what I'm doing now is:

`'dsNMDA/dt = -sNMDA/tau_sNMDA + gamma_sNMDA*(1-sNMDA).*instFR'`

and 

`'dinstFR/dt = -(instFR - [(fIcurve_a*@i_total - fIcurve_b) ./ (1 - exp(-fIcurve_d*(fIcurve_a*@i_total - fIcurve_b)))])/instFR_tau'`

are my master equations.

My synaptic connections are like this:

```
i_synaptic_unspecific(X_pre) = g_synaptic/N_pre.*(X_pre*netcon)
@i_total += +i_synaptic_unspecific(X_pre)
```

And my adaptation current is like this:

```
di_adaptation/dt = -i_adaptation/i_adaptation_tau + g_adaptation*X_stvar2
@i_total += -i_adaptation
```

Are you saying that I could in principle use `instFR` instead of `X_stvar2`?

When I try replacing it I get the following error:

`Error: Undefined function or variable 'inst_FR'`. The reason is that inst_FR doesn't get added the prefix of the population name: instFR instead of popName_instFR

This may be a bug, but I thought it was not supported, so I added access like we do for X. Actually, if that is supported, why do we use X at all?

I would actually prefer using the name of the state variable as it is less prone to errors and much clearer, but it doesn't seem to work for me.

Also, for synaptic inputs, how would you specify pre and post-synaptic state variables?

**Comment by kupiqu** [comment]
Ok, I found out how to do it. It doesn't work inside ODEs, one needs to add an intermediate step as follows:

```
rate_term(instFR) = g_adaptation*instFR
di_adaptation/dt = -i_adaptation/i_adaptation_tau + rate_term(instFR)
```

This seems counterintuitive, is there a way to add this feature directly to ODEs as well.

Also, what if one needs to access the presynaptic state variable, is it possible to do it by name instead of X_pre?

**Comment by kupiqu** [comment]
> Also, what if one needs to access the presynaptic state variable, is it possible to do it by name instead of X_pre?

Answering myself, sNMDA_pre just works, great!

Now if we could access other state variables in ODEs, it would be awesome

**Comment by jsherfey** [comment]
The feature should apply to ODEs as well, and I'm surprised it doesn't. That limitation appears to be a bug. I wonder if that bug is present on the master branch as well.

It should be possible to index presynaptic state variables using e.g., `instFR_pre`; however, it may (for now) require creating a function like you did to access the `instFR`.

**Comment by jsherfey** [comment]
If `sNMDA_pre` works in ODEs, then `sNMDA_post` will probably work as a hacky way to access "intrinsic" state variables without having to use the hackier method of creating an auxiliary function.

**Comment by kupiqu** [comment]
Ok, sounds good, I'm going to close this pull request as it doesn't make sense.

Although not super urgent, it would be great if you could investigate the bug in ODEs.

**Comment by kupiqu** [comment]
> If `sNMDA_pre` works in ODEs, then `sNMDA_post` will probably work as a hacky way to access "intrinsic" state variables without having to use the hackier method of creating an auxiliary function.

Please note that in my model, sNMDA does not appear in an ODE (other than in a master equation), so it is in fact a function and then not bitten by the bug. I don't know if it would or not work when added to a ODE, but will check in a sec.

**Comment by kupiqu** [comment]
Trying to check on sNMDA I realized that the bug appears when the state variable does not appear alone: `+ instFR` and instead appears as `*instFR` (+ g_adaptation*instFR), so it seems there is some bug in the parser, not liking `*`...

**Comment by kupiqu** [comment]
Note this only fails in ODEs, it works as it should in functions

**Comment by jsherfey** [comment]
Was your solution a generic aliasing scheme? I.e., if the master equations
had state vars (V, s), would X_stvar_1 alias V and X_stvar_2 alias s? If
so, this might still be a useful addition well worth merging for the same
reason that using X as an alias to the first state var is useful.

**Comment by kupiqu** [comment]
Yes, exactly that


--

Enviat des del telèfon

**Comment by kupiqu** [comment]
> Was your solution a generic aliasing scheme? I.e., if the master equations had state vars (V, s), would X_stvar_1 alias V and X_stvar_2 alias s? If so, this might still be a useful addition well worth merging for the same reason that using X as an alias to the first state var is useful.

@jsherfey, should we reopen the pull request?

**Comment by kupiqu** [comment]
Weirdly enough, this error (`Error: Undefined function or variable 'inst_FR'`) just disappeared. 

It is not the first time that sth similar happened to me. It's like Dynasim current state affects Matlab, so it sometimes fails and one needs to restart Matlab to make everything work fine again. I wonder if this is only my experience or if you experienced something like that.

**Comment by kupiqu** [comment]
> Was your solution a generic aliasing scheme? I.e., if the master equations had state vars (V, s), would X_stvar_1 alias V and X_stvar_2 alias s? If so, this might still be a useful addition well worth merging for the same reason that using X as an alias to the first state var is useful.

I thought this was not relevant from our previous discussion, and unfortunately I removed the commit from my fork and closed the pull request, so there is no way to reopen and accept the pull request now.

If anyone is interested in adding this feature (if aliases are good for any reason instead of explicit names), then the easiest is to apply the patch to the local repo and start over with a new pull request.

**Comment by kupiqu** [comment]
Added with #580

**Pull request closed without merging**
