### PR TITLE
Improve recursiveness in dsPropagateFunctions

### PR DESCRIPTION
**Pull request by kupiqu**

### CODE REVIEW

**Comment by kupiqu** [comment]
- The changes admit working with functions such as:

```
instFR_fIcurve(@i_total) = (fIcurve_a*@i_total - fIcurve_b) ./ (1 - exp(-fIcurve_d*(fIcurve_a*@i_total - fIcurve_b)))
dinstFR/dt = -(instFR - instFR_fIcurve(@i_total))/instFR_tau
```

and

```
m_inf_kca(ca) = 1./(1+exp(-(ca-ca_onset)/ca_slope))
@minf_kca += +m_inf_kca(ca)
tau_kca(@minf_kca) = tau_kca_baseline - tau_kca_f.*@minf_kca
m_kca' = (m_inf_kca(ca) - m_kca)./tau_kca(@minf_kca)
i_kca(m_kca) = -g_kca*m_kca
```

- Improved compatibility with GNU Octave

- Tested with dsDemos and own models

**Comment by kupiqu** [comment]
There is room for further improvement and the second example above is a clear example. Ideally the link shouldn't be necessary and something like the following should be an option:

```
m_inf_kca(ca) = 1./(1+exp(-(ca-ca_onset)/ca_slope))
tau_kca(m_inf_kca(ca)) = tau_kca_baseline - tau_kca_f.*m_inf_kca(ca)
m_kca' = (m_inf_kca(ca) - m_kca)./tau_kca(minf_kca(ca))
i_kca(m_kca) = -g_kca*m_kca
```

or even better:

```
m_inf_kca(ca) = 1./(1+exp(-(ca-ca_onset)/ca_slope))
tau_kca(m_inf_kca) = tau_kca_baseline - tau_kca_f.*m_inf_kca(ca)
m_kca' = (m_inf_kca(ca) - m_kca)./tau_kca(m_inf_kca)
i_kca(m_kca) = -g_kca*m_kca
```

**Comment by kupiqu** [comment]
approval pending on further testing on conditionals

**Comment by kupiqu** [comment]
This actually works:

```
m_inf_kca(ca) = 1./(1+exp(-(ca-ca_onset)/ca_slope))
tau_kca(m_inf_kca) = tau_kca_baseline - tau_kca_f.*m_inf_kca(ca)
m_kca' = (m_inf_kca(ca) - m_kca)./tau_kca(m_inf_kca)
i_kca(m_kca) = -g_kca*m_kca
```

However, this is not recursive beyond the first level as shown with the following example:

```
dummyfunction(ca) = ca
m_inf_kca(dummyfunction) = 1./(1+exp(-(dummyfunction(ca)-ca_onset)/ca_slope))
tau_kca(m_inf_kca) = tau_kca_baseline - tau_kca_f.*m_inf_kca(dummyfunction)
```

**Comment by kupiqu** [comment]
Error message:

```
Error: Index exceeds the number of array elements (0).
         in insert_functions (line 173)
         in dsPropagateFunctions (line 54)
         in dsWriteDynaSimSolver (line 103)
         in dsGetSolveFile (line 173)
         in dsSimulate/tryFn (line 985)
         in dsSimulate (line 831)
         in mfield (line 104)
Index exceeds the number of array elements (0).

Error in dsPropagateFunctions>insert_functions (line 173)
      new_var_list{1} = regexprep(substr(lb(1)+1:R-1),'([\(\)\+\*\.\^])','\\$1');

Error in dsPropagateFunctions (line 54)
    [expressions{i},keep_going]=insert_functions(expressions{i},model.functions,
    varargin{:});

Error in dsWriteDynaSimSolver (line 103)
  model = dsPropagateFunctions(model, varargin{:});

Error in dsGetSolveFile (line 173)
      solve_file_m = dsWriteDynaSimSolver(model,keyvals{:},'filename',solve_file);
      % create DynaSim solver m-file

Error in dsSimulate/tryFn (line 985)
            options.solve_file = dsGetSolveFile(model,studyinfo,options); % store
            name of solver file in options struct

Error in dsSimulate (line 831)
    tryFn(nargout)
```

Will check if there is an "easy" fix

**Comment by jasonsherfey** [comment]
It might work if you pass variables instead of functions, like this:
```
dummyfunction(ca) = ca
m_inf_kca(ca) = 1./(1+exp(-(dummyfunction(ca)-ca_onset)/ca_slope))
tau_kca(ca) = tau_kca_baseline - tau_kca_f.*m_inf_kca(ca)
```
However, that requires keeping track of variables throughout the function hierarchy and is a suboptimal solution for handling recursiveness as we discussed.

**Comment by kupiqu** [comment]
This was much easier to do than anticipated, I simply needed to escape the case when index is empty :)

**Pull request merged**
